name = "TidierErrors"
uuid = "b23b7fb3-9497-4766-a765-92bf16dfef04"
authors = ["rdboyes <randy.boyes@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbbreviatedStackTraces = "ac637c84-cc71-43bf-9c33-c1b4316be3d4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
AbbreviatedStackTraces = "0.3.1"
InteractiveUtils = "1.10"
Markdown = "1.10"
Pkg = "1.10"
Preferences = "1.5.0"
PromptingTools = "0.79.0"
REPL = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.TidierErrors]
__clear__ = ["tidiererrors_llm_model", "tidiererrors_llm_api_key"]
tidiererrors_default_action = "Do nothing"
tidiererrors_errors = "Show Error Message"
tidiererrors_followups = "Yes"
tidiererrors_llm_schema = "openai"
tidiererrors_stacktraces = "Summarized"
tidiererrors_stream = "Yes"

[targets]
test = ["Test"]
